app:
  base-path: /api/v1/catalog

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 8081

spring:
  application:
    name: catalog-service

  devtools:
    livereload:
      port: 35729

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.web.reactive: debug
